---
python_transforms:
  - name: CustomWebhook
    class_name: "CustomWebhook"
    file_path: "transforms/custom_webhook.py"
    convert_query_response: true

queries:
  - name: webhook_artifact
    file_path: "transforms/webhook_artifact.gql"
