query {
    CoreArtifact {
        edges {
            node {
                __typename
                id
                name {
                    value
                }
                bad {
                    value
                }
            }
        }
    }
}